network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:   #配置的网卡名称
      dhcp4: no    #dhcp4关闭
      dhcp6: no    #dhcp6关闭
      addresses: [192.168.1.3/24]   #设置本机IP及掩码
      gateway4: 192.168.1.1   #设置网关
      nameservers:
          addresses: [114.114.114.114, 8.8.8.8, 192.168.1.1]   #设置DNS
